<a href="https://colab.research.google.com/github/LaisST/FIAP_202501_HandsOn_data_analytics/blob/main/FIAP_Algebra_Linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# INTRODUÇÃO A ÁLGEBRA LINEAR PARA CIENTISTA DE DADOS

In [9]:
#Importação das bibliotecas
import numpy as np

In [10]:
#Construir a matriz dos coeficientes
A = np.array([[2,3],
              [5,7]])

In [11]:
B = np.array([8,19])

In [12]:
#Resolver o sistema
solucao = np.linalg.solve(A,B)

print(f"Valores de x e y: {solucao}")

Valores de x e y: [1. 2.]


### Usando o Sympy

In [13]:
from sympy import symbols, Eq, solve

In [14]:
#Definir as variáveis
x, y = symbols('x y')

#Definir as equações
eq1 = Eq(2*x + 3*y, 8)
eq2 = Eq(5*x + 7*y, 19)

#Resolver o sistema
solucao = solve((eq1, eq2), (x, y))
print(solucao)

{x: 1, y: 2}


## Matrizes

In [15]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

C = np.dot(A, B)

print(C)


[[ 58  64]
 [139 154]]


In [16]:
#Criar matrizes A e B
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

print(f'Matriz A:\n {A}')
print(f'Matriz B:\n {B}')

Matriz A:
 [[1 2]
 [3 4]]
Matriz B:
 [[5 6]
 [7 8]]


In [17]:
#Adição de matrizes
#C = A + B
C = np.add(A, B)
print(f'A soma das matrizes é: \n{C}')

A soma das matrizes é: 
[[ 6  8]
 [10 12]]


In [18]:
#Subtração de matrizes
#D = A - B
D = np.subtract(A, B)

print(f'A subtração das matrizes é:\n{D}')

A subtração das matrizes é:
[[-4 -4]
 [-4 -4]]


## Espaço Vetorial

In [19]:
#Espaço Vetorial
import numpy as np

#Definir dois vetores em R²
V1 = np.array([1,2])
V2 = np.array([3,4])

In [20]:
#Soma de vetores
soma = V1 + V2
print(f'Soma dos vetores:{soma}')

Soma dos vetores:[4 6]


In [21]:
#Multiplicação por escalar
escalar = 2
multiplicacao = escalar * V1
print(f'Multiplicação por escalar: {multiplicacao}')

Multiplicação por escalar: [2 4]


In [23]:
#Autovalor e Autovetor
#Definição da matriz A
A = np.array([[4,-2],
              [1,1]])

In [24]:
#Cálculo dos autovalores e autovetores

In [25]:
autovalores, autovetores = np.linalg.eig(A)

print(f'Autovalores: {autovalores}')
print(f'Autovetores:\n{autovetores}')

Autovalores: [3. 2.]
Autovetores:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]
